#!/bin/bash

# Universal aliases for my arch machines
alias sudo="doas"
alias syncup="doas pacman -Syy"
alias upgrade="yay -Syu"
alias myip="curl ipinfo.io"
alias autoremove="doas bash ~/scripts/arch-autoremove.sh"
alias cl="clear"
alias cls="clear"
alias ex="exit"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias la="ls -a"
alias ll="ls -l"
alias lla="ls -la"
alias cll="clear && ls -l"
alias clla="clear && ls -la"
alias monblk="watch -n2 lsblk"
alias cpf="clear && pfetch"
alias mkdir="mkdir -v"
alias mkd="mkdir -pv"
alias cpumon="watch -n1 'cat /proc/cpuinfo | grep \"^[c]pu MHz\" ; sensors'"
alias tempmon="watch -n1 'sensors | grep \"Tccd1:\"'"
alias kdbx-up="cd ~/Keepassdb && git add . && git commit -m 'archbox' && git push && cd ~"
alias kdbx-dn="cd ~/Keepassdb && git pull && cd ~"
alias rmatrix="cmatrix -abk -C cyan"
alias doasedit="sh ~/scripts/doasedit"
