#!/bin/bash
# this script changes the convention of BSD cp to GNU cp for rsync
# copy to somewhere in the path and add this script as an alias to rsync
new_args=()
for i in "${@}"; do
	case "${i}" in
		/)
			i="/"
		;;
		*/)
			i="${i%/}"
		;;
		esac
	new_args+=("{i}")
done
exec rsync "${new_args[@]}"
