; =====================================
; Patrick's Polybar configuration
; =====================================
[colors]
background = #282A2E
background-alt = #373B41
foreground = #FFFFFF
primary = #999EFF
secondary = #8ABEB7
alert = #A54242
disabled = #707880
separator = #4A4FAE

[bar/archbox-bar1]
monitor = DVI-0 
bottom = true
width = 100%
height = 24pt
radius = 6
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 3pt
border-color = #00000000
padding-left = 3
padding-right = 1
module-margin = 1
separator = %{T2}|%{T-}
separator-foreground = ${colors.separator}
font-0 = SF Pro Display:style=Semibold:size=11;1
font-1 = SF Pro Display:style=Semibold:antialias=false:size=16;1
font-2 = Material\-Design\-Iconic\-Font:style=Design-Iconic-Font:size=14;1
modules-left = kitty nautilus librewolf keepass libvirt libreoffice steam xworkspaces
modules-right = pulseaudio memory cpu archboxtemp wlan date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
tray-position = center

[bar/archbox-bar2]
monitor = HDMI-0
bottom = true
width = 100%
height = 24pt
radius = 6
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 3pt
border-color = #00000000
padding-left = 3
padding-right = 1
module-margin = 1
separator = %{T2}|%{T-}
separator-foreground = ${colors.separator}
font-0 = SF Pro Display:style=Semibold:size=11;1
font-1 = SF Pro Display:style=Semibold:antialias=false:size=16;1
font-2 = Material\-Design\-Iconic\-Font:style=Design-Iconic-Font:size=14;1
modules-left = kitty nautilus librewolf keepass snes xworkspaces
modules-right = pulseaudio memory cpu archboxtemp wlan date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
;tray-position = center

[bar/arch-2im-bar]
monitor = HDMI-1
bottom = true
width = 100%
height = 24pt
radius = 6
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 3pt
border-color = #00000000
padding-left = 3
padding-right = 1
module-margin = 1
separator = %{T2}|%{T-}
separator-foreground = ${colors.separator}
font-0 = SF Pro Display:style=Semibold:size=11;1
font-1 = SF Pro Display:style=Semibold:antialias=false:size=16;1
font-2 = Material\-Design\-Iconic\-Font:style=Design-Iconic-Font:size=14;1
modules-left = kitty librewolf keepass libreoffice xworkspaces
modules-right = pulseaudio memory cpu eth date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
tray-position = center

[bar/archpad-bar1]
monitor = eDP-1
bottom = true
width = 100%
height = 24pt
radius = 6
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 3pt
border-color = #00000000
padding-left = 1
padding-right = 1
module-margin = 1
separator = %{T2}|%{T-}
separator-foreground = ${colors.separator}
font-0 = SF Pro Display:style=Semibold:size=11;1
font-1 = SF Pro Display:style=Semibold:antialias=false:size=16;1
font-2 = Material\-Design\-Iconic\-Font:style=Design-Iconic-Font:size=14;1
modules-left = kitty librewolf keepass libvirt libreoffice xworkspaces
modules-right = pulseaudio memory cpu archpadtemp battery0 battery1 wlan date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
tray-position = left

[bar/archpad-bar2]
monitor = DP-2
bottom = true
width = 100%
height = 24pt
radius = 6
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 3pt
border-color = #00000000
padding-left = 1
padding-right = 1
module-margin = 1
separator = %{T2}|%{T-}
separator-foreground = ${colors.separator}
font-0 = SF Pro Display:style=Semibold:size=11;1
font-1 = SF Pro Display:style=Semibold:antialias=false:size=16;1
font-2 = Material\-Design\-Iconic\-Font:style=Design-Iconic-Font:size=14;1
modules-left = kitty librewolf keepass libvirt libreoffice xworkspaces
modules-right = pulseaudio memory cpu archpadtemp battery0 battery1 wlan date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[bar/iarch-bar]
bottom = true
width = 100%
height = 24pt
radius = 6
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 3pt
border-color = #00000000
padding-left = 1
padding-right = 1
module-margin = 1
separator = %{T2}|%{T-}
separator-foreground = ${colors.separator}
font-0 = SF Pro Display:style=Semibold:size=11;1
font-1 = SF Pro Display:style=Semibold:antialias=false:size=16;1
font-2 = Material\-Design\-Iconic\-Font:style=Design-Iconic-Font:size=14;1
modules-left =  xworkspaces
modules-right = memory cpu date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted =  muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
;format-prefix = "RAM "
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
; icon 1
;format-prefix = " "
; icon 2
format-prefix = ""
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F49E9E}%ifname%%{F#FF4242}  

[module/wlan]
inherit = network-base
interface-type = wireless
;label-connected = %{F#999EFF}%ifname%%{F-} %essid% %local_ip%
label-connected = %{F#65FF75} %local_ip%%{F-}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#999EFF}%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = "   %Y.%m.%d    %H:%M  "

label = %date%
label-foreground = ${colors.foreground}

[module/archboxtemp]
type = internal/temperature
interval = 1
hwmon-path = /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon0/temp3_input
warn-temperature = 96
label = %{F#999EFF}%{F-} %temperature-c%

[module/archpadtemp]
type = internal/temperature
interval = 1
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon6/temp1_input
warn-temperature = 96
label = %{F#999EFF}%{F-} %temperature-c%

[module/battery0]
time-format = %H:%M
type = internal/battery
full-at = 100
battery = BAT0
adapter = ADP1
label-charging = %{F#FF9C4C} %percentage%% %{F-}
label-discharging = %{F#999EFF}%{F-} %percentage%%
label-full = %{F#65ff75} 100%%{F-}

[module/battery1]
time-format = %H:%M
type = internal/battery
full-at = 100
battery = BAT1
adapter = ADP1
label-charging = %{F#FF9C4C} %percentage%% %{F-}
label-discharging = %{F#999EFF}%{F-} %percentage%%
label-full = %{F#65ff75} 100%%{F-}
#label-discharging = %{F#999EFF}BAT1%{F-} %percentage%% %{F#FF8D47}%time% REM%{F-}

[module/librewolf]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo "Librewolf"
initial = 1
click-left = exec ~/.config/polybar/librewolf.sh && sleep 1 && polybar-msg hook librewolf-0 1

[module/kitty]
type = custom/ipc
; icon 1
;hook-0 = echo ""
; icon 2
hook-0 = echo ""
; icon 3
;hook-0 = echo ""
; icon-4
;hook-0 = echo ""
hook-1 = echo "Kitty"
initial = 1
click-left = exec ~/.config/polybar/kitty.sh && sleep 1 && polybar-msg hook kitty-0 1

[module/steam]
type = custom/ipc
; icon 1
;hook-0 = echo ""
; icon 2
hook-0 = echo ""
hook-1 = echo "Steam"
initial = 1
click-left = exec ~/.config/polybar/steam.sh && sleep 1 && polybar-msg hook steam-0 1

[module/libvirt]
type = custom/ipc
; icon 1
;hook-0 = echo ""
; icon 2
;hook-0 = echo ""
; icon 3
hook-0 = echo ""
hook-1 = echo "Virt-Manager"
initial = 1
click-left = exec ~/.config/polybar/virt-manager.sh && sleep 1 && polybar-msg hook libvirt-0 1

[module/keepass]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo "KeepassXC"
initial = 1
click-left = exec ~/.config/polybar/keepassxc.sh && sleep 1 && polybar-msg hook keepass-0 1

[module/libreoffice]
type = custom/ipc
hook-0 = echo "" 
hook-1 = echo "LibreOffice"
initial = 1
click-left = exec ~/.config/polybar/libreoffice.sh && sleep 1 && polybar-msg hook libreoffice-0 1 

[module/nautilus]
type = custom/ipc
hook-0 = echo "" 
hook-1 = echo "Nautilus"
initial = 1
click-left = exec ~/.config/polybar/nautilus.sh && sleep 1 && polybar-msg hook nautilus-0 1 

[module/snes]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo "snes9x"
initial = 1
click-left = exec ~/.config/polybar/snes9x-gtk.sh && sleep 1 && polybar-msg hook snes-0 1

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
